/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HolodockRouteImport } from './routes/holodock'
import { Route as StudioWaitlistRouteImport } from './routes/studio.waitlist'
import { Route as WaitlistIndexRouteImport } from './routes/waitlist.index'
import { Route as WaitlistConfirmedRouteImport } from './routes/waitlist.confirmed'
import { Route as WaitlistUnsubscribeRouteImport } from './routes/waitlist.unsubscribe'
import { Route as WaitlistUnsubscribedRouteImport } from './routes/waitlist.unsubscribed'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HolodockRoute = HolodockRouteImport.update({
  id: '/holodock',
  path: '/holodock',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioWaitlistRoute = StudioWaitlistRouteImport.update({
  id: '/studio/waitlist',
  path: '/studio/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitlistIndexRoute = WaitlistIndexRouteImport.update({
  id: '/waitlist/',
  path: '/waitlist/',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitlistConfirmedRoute = WaitlistConfirmedRouteImport.update({
  id: '/waitlist/confirmed',
  path: '/waitlist/confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitlistUnsubscribeRoute = WaitlistUnsubscribeRouteImport.update({
  id: '/waitlist/unsubscribe',
  path: '/waitlist/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitlistUnsubscribedRoute = WaitlistUnsubscribedRouteImport.update({
  id: '/waitlist/unsubscribed',
  path: '/waitlist/unsubscribed',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/holodock': typeof HolodockRoute
  '/studio/waitlist': typeof StudioWaitlistRoute
  '/waitlist/confirmed': typeof WaitlistConfirmedRoute
  '/waitlist/unsubscribe': typeof WaitlistUnsubscribeRoute
  '/waitlist/unsubscribed': typeof WaitlistUnsubscribedRoute
  '/waitlist/': typeof WaitlistIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/holodock': typeof HolodockRoute
  '/studio/waitlist': typeof StudioWaitlistRoute
  '/waitlist/confirmed': typeof WaitlistConfirmedRoute
  '/waitlist/unsubscribe': typeof WaitlistUnsubscribeRoute
  '/waitlist/unsubscribed': typeof WaitlistUnsubscribedRoute
  '/waitlist': typeof WaitlistIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/holodock': typeof HolodockRoute
  '/studio/waitlist': typeof StudioWaitlistRoute
  '/waitlist/confirmed': typeof WaitlistConfirmedRoute
  '/waitlist/unsubscribe': typeof WaitlistUnsubscribeRoute
  '/waitlist/unsubscribed': typeof WaitlistUnsubscribedRoute
  '/waitlist/': typeof WaitlistIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/holodock'
    | '/studio/waitlist'
    | '/waitlist/confirmed'
    | '/waitlist/unsubscribe'
    | '/waitlist/unsubscribed'
    | '/waitlist/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/holodock'
    | '/studio/waitlist'
    | '/waitlist/confirmed'
    | '/waitlist/unsubscribe'
    | '/waitlist/unsubscribed'
    | '/waitlist'
  id:
    | '__root__'
    | '/'
    | '/holodock'
    | '/studio/waitlist'
    | '/waitlist/confirmed'
    | '/waitlist/unsubscribe'
    | '/waitlist/unsubscribed'
    | '/waitlist/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HolodockRoute: typeof HolodockRoute
  StudioWaitlistRoute: typeof StudioWaitlistRoute
  WaitlistConfirmedRoute: typeof WaitlistConfirmedRoute
  WaitlistUnsubscribeRoute: typeof WaitlistUnsubscribeRoute
  WaitlistUnsubscribedRoute: typeof WaitlistUnsubscribedRoute
  WaitlistIndexRoute: typeof WaitlistIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holodock': {
      id: '/holodock'
      path: '/holodock'
      fullPath: '/holodock'
      preLoaderRoute: typeof HolodockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/waitlist': {
      id: '/studio/waitlist'
      path: '/studio/waitlist'
      fullPath: '/studio/waitlist'
      preLoaderRoute: typeof StudioWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waitlist/': {
      id: '/waitlist/'
      path: '/waitlist'
      fullPath: '/waitlist/'
      preLoaderRoute: typeof WaitlistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waitlist/confirmed': {
      id: '/waitlist/confirmed'
      path: '/waitlist/confirmed'
      fullPath: '/waitlist/confirmed'
      preLoaderRoute: typeof WaitlistConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waitlist/unsubscribe': {
      id: '/waitlist/unsubscribe'
      path: '/waitlist/unsubscribe'
      fullPath: '/waitlist/unsubscribe'
      preLoaderRoute: typeof WaitlistUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waitlist/unsubscribed': {
      id: '/waitlist/unsubscribed'
      path: '/waitlist/unsubscribed'
      fullPath: '/waitlist/unsubscribed'
      preLoaderRoute: typeof WaitlistUnsubscribedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HolodockRoute: HolodockRoute,
  StudioWaitlistRoute: StudioWaitlistRoute,
  WaitlistConfirmedRoute: WaitlistConfirmedRoute,
  WaitlistUnsubscribeRoute: WaitlistUnsubscribeRoute,
  WaitlistUnsubscribedRoute: WaitlistUnsubscribedRoute,
  WaitlistIndexRoute: WaitlistIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
